export const recipeConstants = {
    GET_RECIPE_LIST_REQUEST: "GET_RECIPE_LIST_REQUEST",
    GET_RECIPE_LIST_SUCCESS: "GET_RECIPE_LIST_SUCCESS",
    GET_RECIPE_LIST_ERROR: "GET_RECIPE_LIST_ERROR",

    GET_RECIPE_DETAIL_REQUEST: "GET_RECIPE_DETAIL_REQUEST",
    GET_RECIPE_DETAIL_SUCCESS: "GET_RECIPE_DETAIL_SUCCESS",
    GET_RECIPE_DETAIL_ERROR: "GET_RECIPE_DETAIL_ERROR",

    GET_CATEGORY_LIST_REQUEST: "GET_CATEGORY_LIST_REQUEST",
    GET_CATEGORY_LIST_SUCCESS: "GET_CATEGORY_LIST_SUCCESS",
    GET_CATEGORY_LIST_ERROR: "GET_CATEGORY_LIST_ERROR",

    ADD_RECIPE_REQUEST: "ADD_RECIPE_REQUEST",
    ADD_RECIPE_SUCCESS: "ADD_RECIPE_SUCCESS",
    ADD_RECIPE_ERROR: "ADD_RECIPE_ERROR",

    UPDATE_RECIPE_REQUEST: "UPDATE_RECIPE_REQUEST",
    UPDATE_RECIPE_SUCCESS: "UPDATE_RECIPE_SUCCESS",
    UPDATE_RECIPE_ERROR: "UPDATE_RECIPE_ERROR",
    
    DELETE_RECIPE_REQUEST: "DELETE_RECIPE_REQUEST",
    DELETE_RECIPE_SUCCESS: "DELETE_RECIPE_SUCCESS",
    DELETE_RECIPE_ERROR: "DELETE_RECIPE_ERROR",

    FILTER_RECIPE_LIST: "FILTER_RECIPE_LIST",
    SELECT_SORTING: "SELECT_SORTING",

    EDIT_CURRENT_RECIPE: "EDIT_CURRENT_RECIPE",

    SHOW_CONSENT_DIALOG: "SHOW_CONSENT_DIALOG",
    HIDE_CONSENT_DIALOG: "HIDE_CONSENT_DIALOG",

    SHOW_SNACKBAR: "SHOW_SNACKBAR",
    HIDE_SNACKBAR: "HIDE_SNACKBAR",

    AUTH_LOGIN: "AUTH_LOGIN",
    AUTH_LOGIN_REQUEST: "AUTH_LOGIN_REQUEST",
    AUTH_LOGIN_ERROR: "AUTH_LOGIN_ERROR",

    AUTH_LOGOUT: "AUTH_LOGOUT",

    GET_PROFILE_RECIPE_LIST_REQUEST: "GET_PROFILE_RECIPE_LIST_REQUEST",
    GET_PROFILE_RECIPE_LIST_SUCCESS: "GET_PROFILE_RECIPE_LIST_SUCCESS",
    GET_PROFILE_RECIPE_LIST_ERROR: "GET_PROFILE_RECIPE_LIST_ERROR",

    GET_LIKED_RECIPE_LIST_REQUEST: "GET_LIKED_RECIPE_LIST_REQUEST",
    GET_LIKED_RECIPE_LIST_SUCCESS: "GET_LIKED_RECIPE_LIST_SUCCESS",
    GET_LIKED_RECIPE_LIST_ERROR: "GET_LIKED_RECIPE_LIST_ERROR",

    LIKE_RECIPE_REQUEST: "LIKE_RECIPE_REQUEST",
    LIKE_RECIPE_SUCCESS: "LIKE_RECIPE_SUCCESS",
    LIKE_RECIPE_ERROR: "LIKE_RECIPE_ERROR",

    UNLIKE_RECIPE_REQUEST: "UNLIKE_RECIPE_REQUEST",
    UNLIKE_RECIPE_SUCCESS: "UNLIKE_RECIPE_SUCCESS",
    UNLIKE_RECIPE_ERROR: "UNLIKE_RECIPE_ERROR",

    LIKE_CURRENT_RECIPE_REQUEST: "LIKE_CURRENT_RECIPE_REQUEST",
    LIKE_CURRENT_RECIPE_SUCCESS: "LIKE_CURRENT_RECIPE_SUCCESS",
    LIKE_CURRENT_RECIPE_ERROR: "LIKE_CURRENT_RECIPE_ERROR",

    UNLIKE_CURRENT_RECIPE_REQUEST: "UNLIKE_CURRENT_RECIPE_REQUEST",
    UNLIKE_CURRENT_RECIPE_SUCCESS: "UNLIKE_CURRENT_RECIPE_SUCCESS",
    UNLIKE_CURRENT_RECIPE_ERROR: "UNLIKE_CURRENT_RECIPE_ERROR",
};

export const sorting = {
    DATE_ASCENDING: "DATE_ASCENDING",
    DATE_DESCENDING: "DATE_DESCENDING",
}